version: '3.3'

services:

  django_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: thepass
      POSTGRES_USER: django
    ports:
      - 5432:5432

  django_server:
    build: ./django/src
    depends_on:
      - django_db

  nginx_server:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - django_server
