FROM python:3.5-slim

WORKDIR /producer
ADD . /producer

ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "-u", "producer.py"]
CMD ["\"HELLO WORLD\""]
