version: '3.3'

services:

  django_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: thepass
      POSTGRES_USER: django
    ports:
      - 5432:5432

  django_server:
    build: ./src
    depends_on:
      - django_db
    ports:
      - 8888:8888
